(G-code generated by FlatCAM Evo vUnstable - Version Date: 2023/6/31)

(Name: mounting_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Friday, 02 October 2026 at 13:05)

(This preprocessor is the default preprocessor.)
(It is made to work with MACH3 compatible motion controllers.)

(Z Start: 2 mm)
(Z End: 15.0 mm)
(X,Y End: 0.0000, 0.0000 mm)
(Steps per circle: 16)
(Preprocessor Excellon: default)

(X range:    2.4250 ...   93.6250  mm)
(Y range:    2.4250 ...   63.6250  mm)

(Spindle Speed: 10000.0 RPM)
G21
G90
G94
G01 F100.00
G01 Z2.0000 F1500
G01 Z2.0000 F1500

G01 F100.00
M03 S10000.0
(SPINUP-PATCHED: spin up during slow G1 moves in the air)
G01 Z5.0000 F60
G01 Z2.0000 F60
G01 Z5.0000 F60
G01 Z2.0000 F60
G01 X4.0250 Y4.0250 F1500
G01 Z-1.7000 F100
G01 Z2.0000 F1500
G01 X4.0250 Y62.0250 F1500
G01 Z-1.7000 F100
G01 Z2.0000 F1500
G01 X92.0250 Y62.0250 F1500
G01 Z-1.7000 F100
G01 Z2.0000 F1500
G01 X92.0250 Y4.0250 F1500
G01 Z-1.7000 F100
G01 Z2.0000 F1500
M05
G01 Z15.00 F1500
G01 X0.0 Y0.0 F1500


